name: "Generic Podcast Generator"
author: "Aiden McCallum"
description: "Generates a feed for a podcast from a YAML file. Developed from a GitHub Certificate Course as well"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "purple"
inputs:
  email:
    description: The commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name: 
    description: The commiter's name
    required: true
    default: ${{ github.actor }}
